export { Dashboard } from './portal/Dashboard.jsx'
export { Analyses } from './portal/Analyses.jsx'
export { Appointments } from './portal/Appointments.jsx'
export { Referrals } from './portal/Referrals.jsx'
export { AIAssistant } from './portal/AIAssistant.jsx'
export { Profile } from './portal/Profile.jsx'
export { AdminPanel } from './portal/AdminPanel.jsx'
export { LabPanel } from './portal/LabPanel.jsx'
